---
name: Ironsworn
credit: Shawn Tomkin
url: "https://www.ironswornrpg.com"

attribution: |
  <p>This work is based on <a href="https://www.ironswornrpg.com">Ironsworn</a>, created by
  Shawn Tomkin, and licensed for our use under the
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons
  Attribution-NonCommercial-ShareAlike 4.0 International</a> license.
